### PR TITLE
use PyOpenSSL and eliminate shell-scripts (e.g. EasyRSA)

### PR DESCRIPTION
**Pull request by SvenRoederer**
With this all the operations can be done in python at all and don't require shell-access.
So there will be no reason to run a root-user and it's much more portable

### CODE REVIEW

**Comment by SvenRoederer** [comment]
This code broke with commit e6799b69dd5903735eac1db340ed978da47f5a42, but I did a bit of adapting already in my private repo.
As usual this id WIP-code, which needs to be cleaned and rebased before final merge.

**Comment by booo** [comment]
I think this is going in the right direction. But let us discuss this in person and merge this once it's ready.

**Comment by SvenRoederer** [comment]
This code is running for the tunnel-berlin-CA and seems to work.
Any comments on proceeding?

**Comment by bobster-galore** [comment]
I think it's very nice, when it is only python and not mixed code with funny shell scripts. Since it is already up and running, we should merge it. 
Another advantage is a code basis which can be developed further, w/o having _all_ changes in just one merge.

**Comment by booo** [comment]
Please do not merge this into master. The code in the master branch is currently in production. Once the we changed to the new code base we can merge the code into master.

**Comment by SvenRoederer** [comment]
As we all agree, that dropping these external scripts is the waz to go, we should merge this working code into master.
We can for sure create a "legacy" branch or "use external scripts" branch, into which we can cherry-pick / backport.

That's also the way nearly all other projects work-flow is done, e.g. LEDE, olsrd.

**Comment by SvenRoederer** [comment]
I created the branch "release/use_external-scripts" with the legacy code and switched the current "VPN03-ca" to this branch.

So let's merge this soon.

**Pull request merged**
