### PR TITLE
add validator to check email address length

### PR DESCRIPTION
**Pull request by booo**
This addresses:

https://github.com/freifunk-berlin/ca.berlin.freifunk.net/issues/48

### CODE REVIEW

**Comment by k-nut** [comment]
lgtm 👍

**Comment by k-nut** [comment]
Although: How is this presented to the user if they try to enter an address that is too long?

**Comment by booo** [comment]
"Useful defaults are provided depending on the existence of min and max.":

https://wtforms.readthedocs.io/en/latest/validators.html#built-in-validators

**Comment by k-nut** [comment]
Correct, this is how it looks:

screen shot 2016-11-27 at 19 10 14

**Comment by booo** [comment]
@k-nut are you ok with this? You have the honour of the merge.

**Comment by booo** [comment]
Maybe we should change the length here too: https://github.com/freifunk-berlin/ca.berlin.freifunk.net/blob/master/ca/models.py#L6

I'm not sure what consequences this has.

**Comment by k-nut** [comment]
I think we could change it there as well for consistency but that would lead to a new database migration. It's probably not worth it for now  ¯\_(ツ)_/¯.

**Pull request merged**
