### PR TITLE
Add generation of activation url

### PR DESCRIPTION
**Pull request by slomo**

### CODE REVIEW

**Comment by k-nut** [comment]
@slomo can you fix the three issues that landscape is complaining about? I also think that the `s` variable should be renamed.

**Comment by booo** [comment]
@k-nut This is more like work in progress.

**Comment by slomo** [comment]
So I think we should do some more substantial changes before:
- [ ] split up `app.py` into `app.py`, `models.py`, `routes.py`
- [ ] port certificate generation script to python (so it can be called if the token is verified)

**Comment by k-nut** [comment]
Sounds good to me :)

**Comment by booo** [comment]
I suggest that we add the mail part to the application too.

Maybe we should have a small voice chat (this evening) about the tasks ahead?

**Pull request merged**
