### PR TITLE
Split app.py into multiple files

### PR DESCRIPTION
**Pull request by k-nut**
As proposed py @slomo in  #25 this splits the `app.py` into a couple more files.

Looking forward to your feedback!

### CODE REVIEW

**Comment by booo** [comment]
@k-nut do you want to fix the outstanding issues? If not I suggest that we remove the QuantifiedCode check from the ci.

**Comment by booo** [comment]
Please try to explain why you do things in the commit body. One example is where you did not explain your action is the removal of the pep8 run.

I suggest that we merge this into master without the unfinished implementation of the activiation key. I would like to keep the master branch in a clean and stable state that we can push to production.

Apart form these minor issues I think this a nice contribution!

**Comment by k-nut** [comment]
I agree. I think merging the non-activation-link part into master would make sense.

I'll be more elaborate in the commit body in my next commits, I'm just used to people ignoring them ;)

I removed the pep8 checks from travis because Quantifiedcode and Landscape can take care of that. And I think that having tools like this is a good think. I do think though that the things that quantified code is complaining about are still part of the old code and not related to the restructuring. And those are not so bad so we can leave them in. And since quantified code is only marking the check as failed if _new_ errors occur we can leave this integration in to make sure that future commit stay save.

**Comment by booo** [comment]
@k-nut Can you remove the changes from @slomo from your commit so I can merge this?

**Comment by k-nut** [comment]
ok, I think I managed to remove it. @booo merge or comments are welcome :)

**Comment by booo** [comment]
Next time we should do this in a different way!

**Pull request merged**
