### PR TITLE
manage: add hint of already signed requests of requester

### PR DESCRIPTION
**Pull request by SvenRoederer**
This may help to decide if the request needs a more close check
or if the requester is a well know one.

look like:

> Do you want to generate a certificate for foo, mail@xxx.foo?
>          already signed to this address: 0
> Type y to continue

### CODE REVIEW

**Comment by booo** [comment]
First of all we should implement a reject option.

Why should we make a prejudgement or encourage the admins to make a prejudgement based on the number of granted requests? We should assume that every user has good intentions until they prove us wrong.

**Comment by SvenRoederer** [comment]
+1 for the reject option, as without there is no real need for manual approval. I was always wondering why this option is not given

This idea is not for prejudgement, I personally tend to sign requests more quickly, of a known person. unknown persons I check a bit more / look at the request twice. it's just an indication, that this person seems well known.

**Comment by booo** [comment]
And there you make a prejudgement.

You should sign all requests in the same way and only reject a request if you know for sure the requester abused the system in the past. Otherwise we start to compromise our open culture.

Please close the request if you agree.

**Comment by SvenRoederer** [comment]
If we know a requestor from the past or an in person meeting to and that he is trustworthy my not giving his requests some hint?
This manual process of signing, will be done to check for a valid reason of the requestor. If this process should be "autosign" we don't have to implement a manual check anyways ...

**Comment by SvenRoederer** [comment]
I made this option configurable via config.py. I've spoken with @faust2k on this prejudgement and he doesn't see problem here.
Esp. VPN03 is planned for "Störerhaftungsbefreiung für Freifunker" and the "Förderverein freie Netzwerke e.V." don't want to be a generic VPN-provider. So verifying that the cert will be used in a Freifunk-relation should be checked anyway.

**Comment by SvenRoederer** [comment]
merged as no complains and it is configured to act in the same way as before

**Pull request merged**
