### PR TITLE
Update thanks.html

### PR DESCRIPTION
**Pull request by marcel-sch**
change from given time span to a soon an admin can ;-)

### CODE REVIEW

**Comment by carpodaster** [comment]
`s/einem Admin/einem oder einer Admin*/` ?

**Comment by booo** [comment]
At one point in time we decided to use the underscore for gender aspects. What's wrong with moderator_in?

**Comment by carpodaster** [comment]
+1 for "Moderator_in"

**Comment by marcel-sch** [comment]
ok, what things have to be moderated? that is the reason why I changed it. to be independent from gender I prefer "Administration" or "VPN-Administration"

**Comment by booo** [comment]
What about "das Kollektiv"? I'm also fine with "Administration" but that sounds so official - so German.

**Comment by marcel-sch** [comment]
or delete that part and change it to "Dein Zugang wird zeitnah freigeschaltet und dir per E-Mail zugesendet." ;-)

**Comment by booo** [comment]
@marcel-sch can you implement your idea. I agree that fewer is better!

**Comment by marcel-sch** [comment]
@booo done, i hope in the right way ( i am still learning how to use git)

**Comment by booo** [comment]
@marcel-sch I suggest we don't start to use smilies in commit messages. You could overwrite your old commit by force pushing another change but most of the time that's a bad idea. Rule of thumb: never change the history once you pushed the stuff into the public.

Thanks for the collaboration!

**Pull request merged**
